[project]
name = "final-project-sure-trust"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit>=1.55.0",
    "pandas",
    "numpy",
    "scikit-learn",
    "plotly",
    "openpyxl",
    "seaborn",
    "matplotlib",
    "joblib",
    "groq",
    "mysql-connector-python",
]
